service: mjd-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: me-south-1
  stage: ${opt:stage, 'prod'}  # 👈 Default to 'prod' if no stage is passed
  environment:
    CONNECTION_STRING: ${env:CONNECTION_STRING, ''}
    JWT_SECRET: ${env:JWT_SECRET, ''}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET, ''}
    RATE_FILE: ${env:RATE_FILE, 'backend/MJD-PRICELIST.xlsx'}
    EMAIL_USER: ${env:EMAIL_USER, ''}
    EMAIL_PASS: ${env:EMAIL_PASS, ''}
    STAGE: ${self:provider.stage}
    NODE_OPTIONS: "--enable-source-maps"

  httpApi:
    cors: true
    payload: '2.0'

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - "src/**"
    - "server.js"
    - "package.json"
    - "package-lock.json"
    - "node_modules/**"
    - "backend/MJD-PRICELIST.xlsx"
    - "!node_modules/.cache/**"
    - "!tests/**"
    - "!*.md"
    - "!*.log"
    - "!scripts/**"
