service: mjd-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: me-south-1
  environment:
    CONNECTION_STRING: ${env:CONNECTION_STRING, ''}
    JWT_SECRET:        ${env:JWT_SECRET, ''}
    JWT_REFRESH_SECRET:${env:JWT_REFRESH_SECRET, ''}
    RATE_FILE:         ${env:RATE_FILE, 'backend/MJD-PRICELIST.xlsx'}

  httpApi:
    cors: true

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - "!node_modules/.cache/**"
